// src/constants/styles.js

export const styles = {
  gameContainer: {
    position: "relative",
    height: "100vh",
    width: "100%",
    maxWidth: "600px",
    backgroundColor: "#000040",
    overflow: "hidden",
    margin: "0 auto",
    border: "2px solid #333",
    borderRadius: "8px",
  },
  player: {
    position: "absolute",
    width: "80px",
    height: "80px",
    transform: "translate(-50%, -50%)",
    backgroundImage: "url(/assets/img/SP_xE_D.png)",
    backgroundSize: "contain",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    imageRendering: "pixelated",
  },
  bullet: {
    position: "absolute",
    height: "12px",
    background: "linear-gradient(to bottom, #ffff00, #ff8800)",
    transform: "translate(-50%, -50%)",
    boxShadow: "0 0 5px #fff",
  },
  enemyBullet: {
    position: "absolute",
    width: "12px",
    height: "12px",
    background: "linear-gradient(45deg, #ff0000, #ff8800)",
    borderRadius: "50%",
    transform: "translate(-50%, -50%)",
    boxShadow: "0 0 8px #ff0000",
  },
  enemy: {
    position: "absolute",
    width: "100px",
    height: "100px",
    transform: "translate(-50%, -20%)",
    backgroundImage: "url(/assets/img/EM_xE4.png)",
    backgroundSize: "contain",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    imageRendering: "pixelated",
  },
  boss: {
    position: "absolute",
    width: "150px",
    height: "150px",
    transform: "translate(-50%, -50%)",
    backgroundImage: "url(/assets/img/EM_xE2_D.png)",
    backgroundSize: "contain",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    imageRendering: "pixelated",
  },
  healthBar: {
    position: "absolute",
    top: "5%",
    left: "50%",
    transform: "translateX(-50%)",
    width: "80%",
    height: "20px",
    backgroundColor: "#333",
    border: "2px solid #666",
  },
  healthFill: {
    height: "100%",
    backgroundColor: "#ff0000",
    transition: "width 0.3s",
  },
  hud: {
    position: "absolute",
    top: "16px",
    left: "16px",
    color: "#fff",
    fontFamily: "Press Start 2P, monospace",
    textShadow: "0 0 5px #4488ff",
  },
  gameOver: {
    position: "absolute",
    inset: 0,
    backgroundColor: "rgba(0, 0, 33, 0.85)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
    fontFamily: "Press Start 2P, monospace",
  },
  button: {
    padding: "8px 16px",
    backgroundColor: "#4488ff",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "16px",
    marginTop: "16px",
    fontFamily: "Press Start 2P, monospace",
    textShadow: "0 0 5px #4488ff",
    boxShadow: "0 0 10px #4488ff",
  },
  starLayer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    pointerEvents: "none",
  },
  star: {
    position: "absolute",
    width: "2px",
    height: "2px",
    backgroundColor: "#FFF",
    borderRadius: "50%",
    animation: "fallingStar linear infinite",
  },
  "@keyframes fallingStar": {
    from: {
      transform: "translateY(-100vh)",
    },
    to: {
      transform: "translateY(100vh)",
    },
  },
};
